[0] # air
is_hoverable = false
is_visible = false
is_breakable = false
is_collidable = false
is_replaceable = true
is_transparent = true

[1] # grass
is_hoverable = true
is_visible = true
is_breakable = true
is_collidable = true
is_replaceable = false
is_transparent = false

[2] # dirt
is_hoverable = true
is_visible = true
is_breakable = true
is_collidable = true
is_replaceable = false
is_transparent = false

[3] # stone
is_hoverable = true
is_visible = true
is_breakable = true
is_collidable = true
is_replaceable = false
is_transparent = false

[4] # rose
is_hoverable = true
is_visible = true
is_breakable = true
is_collidable = false
is_replaceable = true
is_transparent = true

[5] # dandelions
is_hoverable = true
is_visible = true
is_breakable = true
is_collidable = false
is_replaceable = true
is_transparent = true

[6] # bedrock
is_hoverable = true
is_visible = true
is_breakable = false
is_collidable = true
is_replaceable = false
is_transparent = false