[package]
name = "floralcraft"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.4"
itertools = "0.14.0"
macroquad = "0.4.14"
noise = "0.9.0"
once_cell = "1.21.3"
rand = { version = "0.9.1", features = ["small_rng"] }
rand_chacha = "0.9.0"
rand_pcg = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
