[package]
name = "floralcraft"
version = "0.1.0"
edition = "2024"

[dependencies]
terrain_data = { git = "https://github.com/penguinawesome1/terrain_data.git" }
mac_dictionary = { git = "https://github.com/penguinawesome1/mac_dictionary.git" }
spriso = { git = "https://github.com/penguinawesome1/spriso.git", tag = "v0.1.0" }
bevy = "0.16.1"
glam = { version = "0.30.4", features = ["serde"] }
itertools = "0.14.0"
noise = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
bincode = "2.0.1"
thiserror = "2.0.12"
ahash = "0.8.12"
indexmap = "2.10.0"
anyhow = "1.0.98"
