[package]
name = "floralcraft"
version = "0.1.0"
edition = "2024"

[dependencies]
floralcraft_terrain = { git = "https://github.com/penguinawesome1/floralcraft_terrain" }
block_dictionary = { git = "https://github.com/penguinawesome1/block_dictionary" }
isometric_projection = { git = "https://github.com/penguinawesome1/isometric_projection" }
bevy = "0.16.1"
glam = { version = "0.30.4", features = ["serde"] }
itertools = "0.14.0"
noise = "0.9.0"
once_cell = "1.21.3"
rand = { version = "0.9.1", features = ["small_rng"] }
rand_pcg = "0.9.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
bincode = "1.3"
thiserror = "2.0.12"
ahash = "0.8.12"
indexmap = "2.10.0"
