[assets.player]
idle = "player/idle.png"
run = "player/run.png"

[assets.blocks]
air = ""
grass = "blocks/grass.png"
dirt = "blocks/dirt.png"
stone = "blocks/stone.png"
bedrock = "blocks/test.png"
missing = "blocks/sunflower.png"

[player]
game_mode = "creative"
gravity_per_second = 130.0
friction_per_second = 0.000_5
acceleration_per_second = 1_500.0
jump_velocity = 50.0
stop_threshold = 0.01
camera_zoom = 2.5

[world]
render_distance = 1
simulation_distance = 0
num_rotations_90_deg_clockwise = 0
target_hover_height = 5.0

[world.generation]
world_mode = "normal"
seed = 2
dirt_height = 4
grass_threshold = 0.2
minimum_air_height = 32
cave_threshold = -0.5

[world.generation.base_noise]
octaves = 2
frequency = 0.01
lacunarity = 2.0
persistence = 0.5

[world.generation.mountain_ridge_noise]
octaves = 3
frequency = 0.008
lacunarity = 2.0
persistence = 0.7

[world.generation.cave_noise]
octaves = 1
frequency = 0.08
lacunarity = 2.0
persistence = 1.0
