[player]
game_mode = "creative"
gravity_per_second = 130.0
friction_per_second = 0.000_5
player_speed = 200.0
jump_velocity = 50.0
camera_zoom_speed = 0.1
camera_decay_rate = 5.0

[world]
render_distance = 12
simulation_distance = 0
num_rotations_90_deg_clockwise = 0
target_hover_height = 5.0

[world.generation]
world_mode = "normal"
seed = 1
dirt_height = 4
grass_threshold = 0.2
lowest_surface_height = 50
highest_surface_height = 100
cave_threshold = 0.03

[world.generation.base_noise]
octaves = 2
frequency = 0.01
lacunarity = 2.0
persistence = 0.5

[world.generation.mountain_ridge_noise]
octaves = 4
frequency = 0.008
lacunarity = 2.1
persistence = 0.65

[world.generation.cave_noise]
octaves = 3
frequency = 0.002
lacunarity = 2.0
persistence = 0.8
