[player]
speed = 20.0

[player.camera]
zoom_speed = 0.1
decay_rate = 5.0

[world]
mode = "normal"
render_distance = 5

[world.terrain]
noise_profile = "DQkGDA=="
seed = 1
scale = 0.5
min_depth = 50
max_depth = 80
dirt_depth = 4
